<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RefundScamBlocker.Core/RefundScamBlocker.Core.csproj" />
    <ProjectReference Include="../RefundScamBlocker.Diagnostics/RefundScamBlocker.Diagnostics.csproj" />
  </ItemGroup>
</Project>

